#!/usr/bin/env zsh
here=$0:A:h
dest=$here/_build
mkdir -p $dest
cp $here/favicon.ico $dest
cp $here/404.html $dest
sed 's/src="rps.js/src="rps.min.js/' $here/index.html >$dest/index.html
uglifyjs -c -m --source-map=$dest/rps.min.js.map --source-map-url=rps.min.js.map -o $dest/rps.min.js $here/rps.js
rsync -r --exclude=README.md $here/static $dest
